//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathEx_Analysis.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PathEx_Analysis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PathEx_Analysis() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PathEx_Analysis.Properties.PathEx_Analysis", typeof(PathEx_Analysis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string cmdCancel {
            get {
                return ResourceManager.GetString("cmdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string cmdOK {
            get {
                return ResourceManager.GetString("cmdOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弧段标识字段 的本地化字符串。
        /// </summary>
        internal static string lblEdgeID {
            get {
                return ResourceManager.GetString("lblEdgeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正向阻力字段 的本地化字符串。
        /// </summary>
        internal static string lblFTWeightField {
            get {
                return ResourceManager.GetString("lblFTWeightField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结点标识字段 的本地化字符串。
        /// </summary>
        internal static string lblNodeID {
            get {
                return ResourceManager.GetString("lblNodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反向阻力字段 的本地化字符串。
        /// </summary>
        internal static string lblTFWeightField {
            get {
                return ResourceManager.GetString("lblTFWeightField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结点选择容限 的本地化字符串。
        /// </summary>
        internal static string lblTolerance {
            get {
                return ResourceManager.GetString("lblTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络分析 的本地化字符串。
        /// </summary>
        internal static string MainForm {
            get {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络分析环境设置 的本地化字符串。
        /// </summary>
        internal static string mnuAnalystSetting {
            get {
                return ResourceManager.GetString("mnuAnalystSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string mnuFile {
            get {
                return ResourceManager.GetString("mnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络分析 的本地化字符串。
        /// </summary>
        internal static string mnuNetAnalyst {
            get {
                return ResourceManager.GetString("mnuNetAnalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开数据源 的本地化字符串。
        /// </summary>
        internal static string mnuOpenDs {
            get {
                return ResourceManager.GetString("mnuOpenDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 漫游 的本地化字符串。
        /// </summary>
        internal static string mnuPan {
            get {
                return ResourceManager.GetString("mnuPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最短路径分析 的本地化字符串。
        /// </summary>
        internal static string mnuPath {
            get {
                return ResourceManager.GetString("mnuPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全幅 的本地化字符串。
        /// </summary>
        internal static string mnuViewEntire {
            get {
                return ResourceManager.GetString("mnuViewEntire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图操作 的本地化字符串。
        /// </summary>
        internal static string mnuViewMap {
            get {
                return ResourceManager.GetString("mnuViewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自由缩放 的本地化字符串。
        /// </summary>
        internal static string mnuZoomFree {
            get {
                return ResourceManager.GetString("mnuZoomFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        internal static string mnuZoomIn {
            get {
                return ResourceManager.GetString("mnuZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        internal static string mnuZoomOut {
            get {
                return ResourceManager.GetString("mnuZoomOut", resourceCulture);
            }
        }
    }
}
